# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  alerter-bin = {
    pname = "alerter-bin";
    version = "26.5";
    src = fetchurl {
      url = "https://github.com/vjeantet/alerter/releases/download/v26.5/alerter-26.5.zip";
      sha256 = "sha256-EfY83cm7P4VU7Zt2JjKhIM+nvuBePAnWVzSCPgnSTxA=";
    };
  };
  apfel-bin = {
    pname = "apfel-bin";
    version = "1.0.5";
    src = fetchurl {
      url = "https://github.com/Arthur-Ficial/apfel/releases/download/v1.0.5/apfel-1.0.5-arm64-macos.tar.gz";
      sha256 = "sha256-etEOYkYVPm08SRE3nuKcDigS7lCkUUgMacOl/sLv/1A=";
    };
  };
  codex-aarch64-darwin-bin = {
    pname = "codex-aarch64-darwin-bin";
    version = "rust-v0.133.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.133.0/codex-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-E8eDYr7/gUt93hbtdWN2I2d3Zphp3eRL0jJnNQDfaFM=";
    };
  };
  codex-aarch64-linux-bin = {
    pname = "codex-aarch64-linux-bin";
    version = "rust-v0.133.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.133.0/codex-aarch64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-Jov+jPgVSUD+olbfdc1EHFSgxx5sjM1Fqz92/yi6FBM=";
    };
  };
  codex-x86_64-linux-bin = {
    pname = "codex-x86_64-linux-bin";
    version = "rust-v0.133.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.133.0/codex-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-0GAZq5w10oG3jcLrsq5VwruX6hG/f0Urr+OQ7dsANO8=";
    };
  };
  confluence-cli = {
    pname = "confluence-cli";
    version = "v1.30.2";
    src = fetchFromGitHub {
      owner = "pchuri";
      repo = "confluence-cli";
      rev = "v1.30.2";
      fetchSubmodules = false;
      sha256 = "sha256-ZN2nD4TGRxe/dAzFWRsDud1Z1xS0u+4a2+r2H8TDw14=";
    };
  };
  displayplacer = {
    pname = "displayplacer";
    version = "v1.4.0";
    src = fetchFromGitHub {
      owner = "jakehilborn";
      repo = "displayplacer";
      rev = "v1.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-BYq8lrS8yE9ARCdAvZxiuC/2vRv6uha++WwKfM37gC0=";
    };
  };
  errorformat = {
    pname = "errorformat";
    version = "223c26dbe2122cc5ce2f3b47400ceaca2b50c496";
    src = fetchFromGitHub {
      owner = "reviewdog";
      repo = "errorformat";
      rev = "223c26dbe2122cc5ce2f3b47400ceaca2b50c496";
      fetchSubmodules = false;
      sha256 = "sha256-kPWojRA7uw8Xv3LDMJRyVB+TpQohmKRrmuRyW+vNWM4=";
    };
  };
  gf-cli = {
    pname = "gf-cli";
    version = "855f571b696373718b5108599c1b0be115c79b0c";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "gf-cli";
      rev = "855f571b696373718b5108599c1b0be115c79b0c";
      fetchSubmodules = false;
      sha256 = "sha256-MtNJ78nVGWGtnQ9ECNi4IzF0ivFg6MZ358ViQDzwCxs=";
    };
  };
  gitbucket = {
    pname = "gitbucket";
    version = "4.46.1";
    src = fetchurl {
      url = "https://github.com/gitbucket/gitbucket/releases/download/4.46.1/gitbucket.war";
      sha256 = "sha256-Vp5naUameav5XhJX1ERCZH0QiWuSuU7QIgX9ADRUdXU=";
    };
  };
  gogcli = {
    pname = "gogcli";
    version = "v0.12.0";
    src = fetchFromGitHub {
      owner = "steipete";
      repo = "gogcli";
      rev = "v0.12.0";
      fetchSubmodules = false;
      sha256 = "sha256-KtjqZLR4Uf77865IGHFmcjwpV8GWkiaV7fBeTrsx93E=";
    };
  };
  gotmplfmt = {
    pname = "gotmplfmt";
    version = "50f0bcb79afc1d7ee8e73ab996b0617e541dc0cd";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "gotmplfmt";
      rev = "50f0bcb79afc1d7ee8e73ab996b0617e541dc0cd";
      fetchSubmodules = false;
      sha256 = "sha256-z1AFVLo8c1EB4vibyL7bwDguTVQXOgPHvXF42YpW8lA=";
    };
  };
  gws-aarch64-darwin-bin = {
    pname = "gws-aarch64-darwin-bin";
    version = "v0.22.5";
    src = fetchurl {
      url = "https://github.com/googleworkspace/cli/releases/download/v0.22.5/google-workspace-cli-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-HSqf/VvJssLEtIYw2vCC+tE9nlfXQZiKLCSO7VYvfaw=";
    };
  };
  gws-aarch64-linux-bin = {
    pname = "gws-aarch64-linux-bin";
    version = "v0.22.5";
    src = fetchurl {
      url = "https://github.com/googleworkspace/cli/releases/download/v0.22.5/google-workspace-cli-aarch64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-lEkCldlYDh6IV05xWgoWKZF0fRLWL4x7jcyCaLbBzqA=";
    };
  };
  gws-x86_64-linux-bin = {
    pname = "gws-x86_64-linux-bin";
    version = "v0.22.5";
    src = fetchurl {
      url = "https://github.com/googleworkspace/cli/releases/download/v0.22.5/google-workspace-cli-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-3njs29LxqEzKAGOn7LxEAkD8FLbrzLsX9GRreSqMXB8=";
    };
  };
  hev-socks5-server = {
    pname = "hev-socks5-server";
    version = "2.12.0";
    src = fetchgit {
      url = "https://github.com/heiher/hev-socks5-server.git";
      rev = "2.12.0";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [ ];
      sha256 = "sha256-hx0GFshSGImLX4bG73MRH5qhbrCPv3q3qJ7kODBHqLI=";
    };
  };
  hocage = {
    pname = "hocage";
    version = "2211a65fb6e3db817a6911e4653fec8596974a51";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "hocage";
      rev = "2211a65fb6e3db817a6911e4653fec8596974a51";
      fetchSubmodules = false;
      sha256 = "sha256-tTf8/9rYNeUU16zNTJMXUSDIE70m9g2WY6FNYCDpteA=";
    };
  };
  json2table = {
    pname = "json2table";
    version = "45e65ae2200fc38be28439b3397e93a78aa1f97c";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "json2table";
      rev = "45e65ae2200fc38be28439b3397e93a78aa1f97c";
      fetchSubmodules = false;
      sha256 = "sha256-WQLtjLsLr1U1rL3xEfkyeKiCUadibD2Hi112bIGmzQs=";
    };
  };
  kakehashi-aarch64-darwin-bin = {
    pname = "kakehashi-aarch64-darwin-bin";
    version = "v0.5.0";
    src = fetchurl {
      url = "https://github.com/atusy/kakehashi/releases/download/v0.5.0/kakehashi-v0.5.0-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-SfTEA5uPlXluRtLVXoPJ73m2UJjN3ElwqnEPp+zSDpE=";
    };
  };
  kakehashi-aarch64-linux-bin = {
    pname = "kakehashi-aarch64-linux-bin";
    version = "v0.5.0";
    src = fetchurl {
      url = "https://github.com/atusy/kakehashi/releases/download/v0.5.0/kakehashi-v0.5.0-aarch64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-YW3BJWx6GijmlSVO+tMWrA3JyJ+a7fr6bfWyOlZkPy8=";
    };
  };
  kakehashi-x86_64-linux-bin = {
    pname = "kakehashi-x86_64-linux-bin";
    version = "v0.5.0";
    src = fetchurl {
      url = "https://github.com/atusy/kakehashi/releases/download/v0.5.0/kakehashi-v0.5.0-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-/O5ca7o5lG76sFo+4IBoVE5xbtc8gYBExlmzfhMaIVo=";
    };
  };
  kubernetes-mcp-server = {
    pname = "kubernetes-mcp-server";
    version = "v0.0.62";
    src = fetchFromGitHub {
      owner = "containers";
      repo = "kubernetes-mcp-server";
      rev = "v0.0.62";
      fetchSubmodules = false;
      sha256 = "sha256-m4oM8KMcDmXwIGaFw+VdnW22kLjt2SaD7qZV4kgTiu8=";
    };
  };
  libduckdb-aarch64-darwin-bin = {
    pname = "libduckdb-aarch64-darwin-bin";
    version = "v1.5.3";
    src = fetchurl {
      url = "https://install.duckdb.org/v1.5.3/libduckdb-osx-universal.zip";
      sha256 = "sha256-OG+OiztLyNEodiMnEh4iBlzkXy7lXvGx9BLOEeDmxR8=";
    };
  };
  libduckdb-aarch64-linux-bin = {
    pname = "libduckdb-aarch64-linux-bin";
    version = "v1.5.3";
    src = fetchurl {
      url = "https://install.duckdb.org/v1.5.3/libduckdb-linux-arm64.zip";
      sha256 = "sha256-FigG1ZHAQx0DHZvfQ9vsxfAHVdoBogZN9o+aaab1ChA=";
    };
  };
  libduckdb-x86_64-linux-bin = {
    pname = "libduckdb-x86_64-linux-bin";
    version = "v1.5.3";
    src = fetchurl {
      url = "https://install.duckdb.org/v1.5.3/libduckdb-linux-amd64.zip";
      sha256 = "sha256-CpJuulvOCrwAEPS5EJEz5EQMt06XvRD9LQ/CpyFiGwU=";
    };
  };
  octorus-aarch64-darwin-bin = {
    pname = "octorus-aarch64-darwin-bin";
    version = "0.6.4";
    src = fetchurl {
      url = "https://github.com/ushironoko/octorus/releases/download/v0.6.4/octorus-0.6.4-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-ptNF4ZBCUdnXviNxDp5GtS/4rRl3mlUrS4CtKUF0Ve0=";
    };
  };
  octorus-aarch64-linux-bin = {
    pname = "octorus-aarch64-linux-bin";
    version = "0.6.4";
    src = fetchurl {
      url = "https://github.com/ushironoko/octorus/releases/download/v0.6.4/octorus-0.6.4-aarch64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-3sAHKMf75uGZD51AEJuvk1ZsPw1tnUYG5i7YXLIhyvI=";
    };
  };
  octorus-x86_64-linux-bin = {
    pname = "octorus-x86_64-linux-bin";
    version = "0.6.4";
    src = fetchurl {
      url = "https://github.com/ushironoko/octorus/releases/download/v0.6.4/octorus-0.6.4-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-Xx3QrWwMkBiZWDV+C7qJyYGJm9Vg746iTNtyYUWXDiA=";
    };
  };
  perl5 = {
    pname = "perl5";
    version = "v5.43.10";
    src = fetchFromGitHub {
      owner = "Perl";
      repo = "perl5";
      rev = "v5.43.10";
      fetchSubmodules = false;
      sha256 = "sha256-339L9trny4j5B/vJ2ljbtVXdLcWwLYyIVo60mnbk+bs=";
    };
  };
  prometheus-jmx-exporter = {
    pname = "prometheus-jmx-exporter";
    version = "1.5.0";
    src = fetchurl {
      url = "https://github.com/prometheus/jmx_exporter/releases/download/1.5.0/jmx_prometheus_javaagent-1.5.0.jar";
      sha256 = "sha256-AxXz9leHYwLGIFqY1ANux3XcpSnF0EGcpg7macaII58=";
    };
  };
  socks5shim = {
    pname = "socks5shim";
    version = "419b8ebb4ece1362e84f95fc05662e27b29ec4ef";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "socks5shim";
      rev = "419b8ebb4ece1362e84f95fc05662e27b29ec4ef";
      fetchSubmodules = false;
      sha256 = "sha256-tfwlK4ie+nVSBPL/BGX5/juph/oOsbNNgHYnEtcbuNI=";
    };
  };
  starlink-exporter = {
    pname = "starlink-exporter";
    version = "v20250818";
    src = fetchFromGitHub {
      owner = "clarkzjw";
      repo = "starlink_exporter";
      rev = "v20250818";
      fetchSubmodules = false;
      sha256 = "sha256-hPbZC3R9i/ftMrZz727ACY09H3cX91OyJ47YgjM/nS4=";
    };
  };
  zlib-rs = {
    pname = "zlib-rs";
    version = "v0.6.3";
    src = fetchFromGitHub {
      owner = "trifectatechfoundation";
      repo = "zlib-rs";
      rev = "v0.6.3";
      fetchSubmodules = false;
      sha256 = "sha256-hNmNLhWfP/fCdCYqa0wIK3ii39kemI7oY8SfjjAqPt8=";
    };
    cargoLock."libz-rs-sys-cdylib/Cargo.lock" = {
      lockFile = ./. + "/sha256-hNmNLhWfP_fCdCYqa0wIK3ii39kemI7oY8SfjjAqPt8=/libz-rs-sys-cdylib/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
