# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  acli-aarch64-darwin-bin = {
    pname = "acli-aarch64-darwin-bin";
    version = "1.3.22-stable";
    src = fetchurl {
      url = "https://acli.atlassian.com/darwin/1.3.22-stable/acli_1.3.22-stable_darwin_arm64.tar.gz";
      sha256 = "sha256-Oppv8bsLzlkCeA4m50ixi5rbRInfZ9iOqHj0t2c5RK0=";
    };
  };
  acli-aarch64-linux-bin = {
    pname = "acli-aarch64-linux-bin";
    version = "1.3.22-stable";
    src = fetchurl {
      url = "https://acli.atlassian.com/linux/1.3.22-stable/acli_1.3.22-stable_linux_arm64.tar.gz";
      sha256 = "sha256-Gp6G0LRqYqjxmSwe+Ys69+mp7j920O+iFf4fLRsv0Tk=";
    };
  };
  acli-x86_64-linux-bin = {
    pname = "acli-x86_64-linux-bin";
    version = "1.3.22-stable";
    src = fetchurl {
      url = "https://acli.atlassian.com/linux/1.3.22-stable/acli_1.3.22-stable_linux_amd64.tar.gz";
      sha256 = "sha256-3p4KYKVW5BGUKLkHL2ynh+dbn5pTiqcevMgITeuMoaY=";
    };
  };
  alerter-bin = {
    pname = "alerter-bin";
    version = "26.5";
    src = fetchurl {
      url = "https://github.com/vjeantet/alerter/releases/download/v26.5/alerter-26.5.zip";
      sha256 = "sha256-EfY83cm7P4VU7Zt2JjKhIM+nvuBePAnWVzSCPgnSTxA=";
    };
  };
  apfel-bin = {
    pname = "apfel-bin";
    version = "1.8.4";
    src = fetchurl {
      url = "https://github.com/Arthur-Ficial/apfel/releases/download/v1.8.4/apfel-1.8.4-arm64-macos.tar.gz";
      sha256 = "sha256-farvPPo3VU2qUat+72qaiMpcd9LwFO7kqzGGKKtPwGE=";
    };
  };
  argocdapp2helmfile = {
    pname = "argocdapp2helmfile";
    version = "ea2dc85271c82b510a320b0d13c420c8894c80ab";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "argocdapp2helmfile";
      rev = "ea2dc85271c82b510a320b0d13c420c8894c80ab";
      fetchSubmodules = false;
      sha256 = "sha256-eoi8d7swuE74MHGyW2tbVZXc4ngShsz+Hxa5CFv/ZXU=";
    };
  };
  asciigraph = {
    pname = "asciigraph";
    version = "v0.10.0";
    src = fetchFromGitHub {
      owner = "guptarohit";
      repo = "asciigraph";
      rev = "v0.10.0";
      fetchSubmodules = false;
      sha256 = "sha256-VRF7wAiFQSL1PLmV0k2NjzuEKwprnS028FM0loTpmaI=";
    };
  };
  aws-sigv4-proxy = {
    pname = "aws-sigv4-proxy";
    version = "v1.12";
    src = fetchFromGitHub {
      owner = "awslabs";
      repo = "aws-sigv4-proxy";
      rev = "v1.12";
      fetchSubmodules = false;
      sha256 = "sha256-U0Jxe52bmV+QaS+mKNdW+VzzCtulRL1ZanbWxp4oqcs=";
    };
  };
  awsigv4-proxy = {
    pname = "awsigv4-proxy";
    version = "10a42826710542f17d0985ce2c18fa8133aba438";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "awsigv4-proxy";
      rev = "10a42826710542f17d0985ce2c18fa8133aba438";
      fetchSubmodules = false;
      sha256 = "sha256-bL6sB3M5edh5AAJe0saiohDcqHzH7jrN7EjqeMYBV/s=";
    };
  };
  clawpatrol = {
    pname = "clawpatrol";
    version = "v0.5.8";
    src = fetchFromGitHub {
      owner = "denoland";
      repo = "clawpatrol";
      rev = "v0.5.8";
      fetchSubmodules = false;
      sha256 = "sha256-TOXWMhJdqDnT/TVCvjBXMjeeAXpQUysepsYvhcXarno=";
    };
  };
  clawpatrol-aarch64-darwin-bin = {
    pname = "clawpatrol-aarch64-darwin-bin";
    version = "v0.5.8";
    src = fetchurl {
      url = "https://github.com/denoland/clawpatrol/releases/download/v0.5.8/clawpatrol-darwin-arm64";
      sha256 = "sha256-m0fp24ifocs170nVNNOzptOlcamK48MFwmRc3MrHYgY=";
    };
  };
  clawpatrol-aarch64-linux-bin = {
    pname = "clawpatrol-aarch64-linux-bin";
    version = "v0.5.8";
    src = fetchurl {
      url = "https://github.com/denoland/clawpatrol/releases/download/v0.5.8/clawpatrol-linux-arm64";
      sha256 = "sha256-OVkloi45+zvZdJmGIjqKXZrFBHo6xDHGl0ccsFUysqM=";
    };
  };
  clawpatrol-x86_64-linux-bin = {
    pname = "clawpatrol-x86_64-linux-bin";
    version = "v0.5.8";
    src = fetchurl {
      url = "https://github.com/denoland/clawpatrol/releases/download/v0.5.8/clawpatrol-linux-amd64";
      sha256 = "sha256-DTFx7UQTw+24xbPHd50m+nogdPnNNrywpiWn/6JE/tc=";
    };
  };
  codex-aarch64-darwin-bin = {
    pname = "codex-aarch64-darwin-bin";
    version = "rust-v0.146.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.146.0/codex-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-J1ATLTAOZPHb/7lePZE/2cnceBK8jhvOXGE1cki3kp4=";
    };
  };
  codex-aarch64-linux-bin = {
    pname = "codex-aarch64-linux-bin";
    version = "rust-v0.146.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.146.0/codex-aarch64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-l1uskVYqvu3rj3ljbVGoZkmzHzSp3mo7ywWVZbbPH4c=";
    };
  };
  codex-x86_64-linux-bin = {
    pname = "codex-x86_64-linux-bin";
    version = "rust-v0.146.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.146.0/codex-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-W6O5QFVDlTCB9mHQhU0mb3biq75R1BNJNVo23nZzd2o=";
    };
  };
  confluence-cli = {
    pname = "confluence-cli";
    version = "v2.19.1";
    src = fetchFromGitHub {
      owner = "pchuri";
      repo = "confluence-cli";
      rev = "v2.19.1";
      fetchSubmodules = false;
      sha256 = "sha256-sbG40BaxoDffbIpRUNgXxXGd6bCJDhzc9/eJjV+YtZs=";
    };
  };
  displayplacer = {
    pname = "displayplacer";
    version = "v1.4.0";
    src = fetchFromGitHub {
      owner = "jakehilborn";
      repo = "displayplacer";
      rev = "v1.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-BYq8lrS8yE9ARCdAvZxiuC/2vRv6uha++WwKfM37gC0=";
    };
  };
  errorformat = {
    pname = "errorformat";
    version = "13bff69235f30fd8b35c60151582584a7d81a50a";
    src = fetchFromGitHub {
      owner = "reviewdog";
      repo = "errorformat";
      rev = "13bff69235f30fd8b35c60151582584a7d81a50a";
      fetchSubmodules = false;
      sha256 = "sha256-L3vdBzvsN+6iHFs1Jvpq4lZcN5KZKCFG0duo29UoKlM=";
    };
  };
  gcx-aarch64-darwin-bin = {
    pname = "gcx-aarch64-darwin-bin";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/grafana/gcx/releases/download/v1.0.0/gcx_1.0.0_darwin_arm64.tar.gz";
      sha256 = "sha256-XCesCNDW2CpjRo119Bv+g1NuF++om2MpB2/LLaBGpnI=";
    };
  };
  gcx-aarch64-linux-bin = {
    pname = "gcx-aarch64-linux-bin";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/grafana/gcx/releases/download/v1.0.0/gcx_1.0.0_linux_arm64.tar.gz";
      sha256 = "sha256-YF9rt0BtFEvRHHL/JWSasXIpaZvlhaJTRgt3OW3FdYU=";
    };
  };
  gcx-x86_64-linux-bin = {
    pname = "gcx-x86_64-linux-bin";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/grafana/gcx/releases/download/v1.0.0/gcx_1.0.0_linux_amd64.tar.gz";
      sha256 = "sha256-yIxllY0Z2D3DoZKipQN+CDB6nHdgGfJCSbifNpycTUE=";
    };
  };
  gf-cli = {
    pname = "gf-cli";
    version = "89564b4b04a01c5fdd9b495e2936f27bed4032db";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "gf-cli";
      rev = "89564b4b04a01c5fdd9b495e2936f27bed4032db";
      fetchSubmodules = false;
      sha256 = "sha256-jdzl9UxGJ/JYbKe4XeSwhHEDa3c6AtMv6AgQir1jNfo=";
    };
  };
  ghtkn-aarch64-darwin-bin = {
    pname = "ghtkn-aarch64-darwin-bin";
    version = "v0.3.5";
    src = fetchurl {
      url = "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v0.3.5/ghtkn_darwin_arm64.tar.gz";
      sha256 = "sha256-106TfMoXGTm7DgLSRAJEBQITco3W8u58gZZzoQxUdRI=";
    };
  };
  ghtkn-aarch64-linux-bin = {
    pname = "ghtkn-aarch64-linux-bin";
    version = "v0.3.5";
    src = fetchurl {
      url = "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v0.3.5/ghtkn_linux_arm64.tar.gz";
      sha256 = "sha256-1/VUZxMotTt+/RtXvlZhvFhbApODdrx/Oj3BjskPLBA=";
    };
  };
  ghtkn-x86_64-linux-bin = {
    pname = "ghtkn-x86_64-linux-bin";
    version = "v0.3.5";
    src = fetchurl {
      url = "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v0.3.5/ghtkn_linux_amd64.tar.gz";
      sha256 = "sha256-hs9yNE1uD5PbZ+lzCuubusg+l8dmUeMwyuZN2NhUNQs=";
    };
  };
  gitbucket = {
    pname = "gitbucket";
    version = "4.46.1";
    src = fetchurl {
      url = "https://github.com/gitbucket/gitbucket/releases/download/4.46.1/gitbucket.war";
      sha256 = "sha256-Vp5naUameav5XhJX1ERCZH0QiWuSuU7QIgX9ADRUdXU=";
    };
  };
  gogcli-aarch64-darwin-bin = {
    pname = "gogcli-aarch64-darwin-bin";
    version = "0.34.1";
    src = fetchurl {
      url = "https://github.com/steipete/gogcli/releases/download/v0.34.1/gogcli_0.34.1_darwin_arm64.tar.gz";
      sha256 = "sha256-kKuRBNVD0WrFNn1AXcYbiGADoRjOfq3dDdc8A2MUFEk=";
    };
  };
  gogcli-aarch64-linux-bin = {
    pname = "gogcli-aarch64-linux-bin";
    version = "0.34.1";
    src = fetchurl {
      url = "https://github.com/steipete/gogcli/releases/download/v0.34.1/gogcli_0.34.1_linux_arm64.tar.gz";
      sha256 = "sha256-hRDbZJLCf3cEv2CvJ2807egbZ9iLb/z5UxU9qEHqo+0=";
    };
  };
  gogcli-x86_64-linux-bin = {
    pname = "gogcli-x86_64-linux-bin";
    version = "0.34.1";
    src = fetchurl {
      url = "https://github.com/steipete/gogcli/releases/download/v0.34.1/gogcli_0.34.1_linux_amd64.tar.gz";
      sha256 = "sha256-pbS+LqY11Mgwly3sHzqQsMoX+cJeemNT0eBo2FBeqYM=";
    };
  };
  gotmpl = {
    pname = "gotmpl";
    version = "c4f96c3f57bd6ce36c581d31b5b4bb82877f4be7";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "gotmpl";
      rev = "c4f96c3f57bd6ce36c581d31b5b4bb82877f4be7";
      fetchSubmodules = false;
      sha256 = "sha256-2rFZZYN+wzf0LKWSx6hbYDG1mtx07o1AHIkpAYsF1Uo=";
    };
  };
  gotmplfmt = {
    pname = "gotmplfmt";
    version = "50f0bcb79afc1d7ee8e73ab996b0617e541dc0cd";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "gotmplfmt";
      rev = "50f0bcb79afc1d7ee8e73ab996b0617e541dc0cd";
      fetchSubmodules = false;
      sha256 = "sha256-z1AFVLo8c1EB4vibyL7bwDguTVQXOgPHvXF42YpW8lA=";
    };
  };
  gws-aarch64-darwin-bin = {
    pname = "gws-aarch64-darwin-bin";
    version = "v0.22.5";
    src = fetchurl {
      url = "https://github.com/googleworkspace/cli/releases/download/v0.22.5/google-workspace-cli-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-HSqf/VvJssLEtIYw2vCC+tE9nlfXQZiKLCSO7VYvfaw=";
    };
  };
  gws-aarch64-linux-bin = {
    pname = "gws-aarch64-linux-bin";
    version = "v0.22.5";
    src = fetchurl {
      url = "https://github.com/googleworkspace/cli/releases/download/v0.22.5/google-workspace-cli-aarch64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-lEkCldlYDh6IV05xWgoWKZF0fRLWL4x7jcyCaLbBzqA=";
    };
  };
  gws-x86_64-linux-bin = {
    pname = "gws-x86_64-linux-bin";
    version = "v0.22.5";
    src = fetchurl {
      url = "https://github.com/googleworkspace/cli/releases/download/v0.22.5/google-workspace-cli-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-3njs29LxqEzKAGOn7LxEAkD8FLbrzLsX9GRreSqMXB8=";
    };
  };
  hev-socks5-server = {
    pname = "hev-socks5-server";
    version = "2.12.0";
    src = fetchgit {
      url = "https://github.com/heiher/hev-socks5-server.git";
      rev = "2.12.0";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-8U6NXHiL3ZFb+HuBPm4RKLyKn8YNOQg7DJivsOv0Y5w=";
    };
  };
  hocage = {
    pname = "hocage";
    version = "43daf740c8695c82509b0ef7a8695822496be5e2";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "hocage";
      rev = "43daf740c8695c82509b0ef7a8695822496be5e2";
      fetchSubmodules = false;
      sha256 = "sha256-arT6NJxHnkJM81QUmoBckOsiryEi+jZL6DGwzBmeg2M=";
    };
  };
  jira-cli = {
    pname = "jira-cli";
    version = "v2.8.1";
    src = fetchFromGitHub {
      owner = "pchuri";
      repo = "jira-cli";
      rev = "v2.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-WMCS1HoX/fGq+F1XBKs0Udco4goBKwnVtpN4Imz1I5M=";
    };
  };
  json2table = {
    pname = "json2table";
    version = "45e65ae2200fc38be28439b3397e93a78aa1f97c";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "json2table";
      rev = "45e65ae2200fc38be28439b3397e93a78aa1f97c";
      fetchSubmodules = false;
      sha256 = "sha256-WQLtjLsLr1U1rL3xEfkyeKiCUadibD2Hi112bIGmzQs=";
    };
  };
  json2toml = {
    pname = "json2toml";
    version = "4f4070151e5e2d18627631070074b05996b61458";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "json2toml";
      rev = "4f4070151e5e2d18627631070074b05996b61458";
      fetchSubmodules = false;
      sha256 = "sha256-ABup53MZL/w5L6G/WEOc9QckKDAOkfoGwOhrja7Woec=";
    };
  };
  kakehashi-aarch64-darwin-bin = {
    pname = "kakehashi-aarch64-darwin-bin";
    version = "v0.9.0";
    src = fetchurl {
      url = "https://github.com/atusy/kakehashi/releases/download/v0.9.0/kakehashi-v0.9.0-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-m6NKN1O+0cVpU4H89c0ep/acd7blWXGpDjw8K6HUTRY=";
    };
  };
  kakehashi-aarch64-linux-bin = {
    pname = "kakehashi-aarch64-linux-bin";
    version = "v0.9.0";
    src = fetchurl {
      url = "https://github.com/atusy/kakehashi/releases/download/v0.9.0/kakehashi-v0.9.0-aarch64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-oi4ENFAN8ak2GiQAww0yitzlqoieEaj46OfYPMT8PAs=";
    };
  };
  kakehashi-x86_64-linux-bin = {
    pname = "kakehashi-x86_64-linux-bin";
    version = "v0.9.0";
    src = fetchurl {
      url = "https://github.com/atusy/kakehashi/releases/download/v0.9.0/kakehashi-v0.9.0-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-Nx75WQ42Xzqb3ehSIIIW0rB/2mT5kfNdI5CdT8rKZ5Q=";
    };
  };
  kubectl-schedsim = {
    pname = "kubectl-schedsim";
    version = "0eedb37cc65ba1a7247a1968419bfa30c99916af";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "kubectl-schedsim";
      rev = "0eedb37cc65ba1a7247a1968419bfa30c99916af";
      fetchSubmodules = false;
      sha256 = "sha256-JctSgAZtl0txU6IaUulcR1G0GwXw3LmIspAMANn3H8I=";
    };
  };
  kubernetes-mcp-server-aarch64-darwin-bin = {
    pname = "kubernetes-mcp-server-aarch64-darwin-bin";
    version = "v0.0.66";
    src = fetchurl {
      url = "https://github.com/containers/kubernetes-mcp-server/releases/download/v0.0.66/kubernetes-mcp-server-darwin-arm64";
      sha256 = "sha256-Ueotf0Us+i+TBCXjsYcCM76vn5LiEF/JIwVWXyk8kio=";
    };
  };
  kubernetes-mcp-server-aarch64-linux-bin = {
    pname = "kubernetes-mcp-server-aarch64-linux-bin";
    version = "v0.0.66";
    src = fetchurl {
      url = "https://github.com/containers/kubernetes-mcp-server/releases/download/v0.0.66/kubernetes-mcp-server-linux-arm64";
      sha256 = "sha256-NMFKAa0IQwLBgYSPhBUbwlhY8IGOJztNsbct5yavHuU=";
    };
  };
  kubernetes-mcp-server-x86_64-linux-bin = {
    pname = "kubernetes-mcp-server-x86_64-linux-bin";
    version = "v0.0.66";
    src = fetchurl {
      url = "https://github.com/containers/kubernetes-mcp-server/releases/download/v0.0.66/kubernetes-mcp-server-linux-amd64";
      sha256 = "sha256-aSp7KDqWFAMR/UbxO4NzZXsum/5mCja7ZDToxC2Jnbw=";
    };
  };
  kwok-aarch64-darwin-bin = {
    pname = "kwok-aarch64-darwin-bin";
    version = "v0.8.0";
    src = fetchurl {
      url = "https://github.com/kubernetes-sigs/kwok/releases/download/v0.8.0/kwok-darwin-arm64";
      sha256 = "sha256-aaBk7JjTeETZ10K1so/1eCVlmpg8zD4gjappSLlNZLo=";
    };
  };
  kwok-aarch64-linux-bin = {
    pname = "kwok-aarch64-linux-bin";
    version = "v0.8.0";
    src = fetchurl {
      url = "https://github.com/kubernetes-sigs/kwok/releases/download/v0.8.0/kwok-linux-arm64";
      sha256 = "sha256-Yo99J3hg9SSip3XCF63MWIKOe1mrCTNoAxV4TxuLDjc=";
    };
  };
  kwok-x86_64-linux-bin = {
    pname = "kwok-x86_64-linux-bin";
    version = "v0.8.0";
    src = fetchurl {
      url = "https://github.com/kubernetes-sigs/kwok/releases/download/v0.8.0/kwok-linux-amd64";
      sha256 = "sha256-9aQ4Wirhud1/isrhjgAqdcDruhJK6dclmqja21BxH0Y=";
    };
  };
  kwokctl-aarch64-darwin-bin = {
    pname = "kwokctl-aarch64-darwin-bin";
    version = "v0.8.0";
    src = fetchurl {
      url = "https://github.com/kubernetes-sigs/kwok/releases/download/v0.8.0/kwokctl-darwin-arm64";
      sha256 = "sha256-kyOlmtucJ4VL0qdmUq0AJYvLtorMQKug3CHjYrZ7fWo=";
    };
  };
  kwokctl-aarch64-linux-bin = {
    pname = "kwokctl-aarch64-linux-bin";
    version = "v0.8.0";
    src = fetchurl {
      url = "https://github.com/kubernetes-sigs/kwok/releases/download/v0.8.0/kwokctl-linux-arm64";
      sha256 = "sha256-WmQrJ9PpdfNgQNIVZAzZD7SmPLb8oK1YZaYbzZyBBRs=";
    };
  };
  kwokctl-x86_64-linux-bin = {
    pname = "kwokctl-x86_64-linux-bin";
    version = "v0.8.0";
    src = fetchurl {
      url = "https://github.com/kubernetes-sigs/kwok/releases/download/v0.8.0/kwokctl-linux-amd64";
      sha256 = "sha256-1XQxZsZXKD1ugnx8TCDKz9kAn9lIMPBnGMp7LHCZRh8=";
    };
  };
  libduckdb-aarch64-darwin-bin = {
    pname = "libduckdb-aarch64-darwin-bin";
    version = "v1.5.5";
    src = fetchurl {
      url = "https://install.duckdb.org/v1.5.5/libduckdb-osx-universal.zip";
      sha256 = "sha256-e1uJFcw4LQcIY2/mOFwM2tWmHJ/4uiY4s+IUFkB4MVU=";
    };
  };
  libduckdb-aarch64-linux-bin = {
    pname = "libduckdb-aarch64-linux-bin";
    version = "v1.5.5";
    src = fetchurl {
      url = "https://install.duckdb.org/v1.5.5/libduckdb-linux-arm64.zip";
      sha256 = "sha256-q+T28AXuC0SKBYMi9CY1hLS9G2+verRje3nur5ePjpw=";
    };
  };
  libduckdb-x86_64-linux-bin = {
    pname = "libduckdb-x86_64-linux-bin";
    version = "v1.5.5";
    src = fetchurl {
      url = "https://install.duckdb.org/v1.5.5/libduckdb-linux-amd64.zip";
      sha256 = "sha256-H7jOOIFX2Eolq+aFqKJSC/AMADIYIZaOS7OY/XZuers=";
    };
  };
  mise-aarch64-darwin-bin = {
    pname = "mise-aarch64-darwin-bin";
    version = "v2026.8.0";
    src = fetchurl {
      url = "https://github.com/jdx/mise/releases/download/v2026.8.0/mise-v2026.8.0-macos-arm64.tar.gz";
      sha256 = "sha256-lO5G7CKwVWByi4nSJ5LLUc3QHBdJEcB5WYnRnjISMRo=";
    };
  };
  mise-aarch64-linux-bin = {
    pname = "mise-aarch64-linux-bin";
    version = "v2026.8.0";
    src = fetchurl {
      url = "https://github.com/jdx/mise/releases/download/v2026.8.0/mise-v2026.8.0-linux-arm64.tar.gz";
      sha256 = "sha256-bYiLo9C1149nZ3GoSEaIW39oX7TRUz8pJweeubdWM6g=";
    };
  };
  mise-x86_64-linux-bin = {
    pname = "mise-x86_64-linux-bin";
    version = "v2026.8.0";
    src = fetchurl {
      url = "https://github.com/jdx/mise/releases/download/v2026.8.0/mise-v2026.8.0-linux-x64.tar.gz";
      sha256 = "sha256-ZBg2A4VPMZt4ZYMFxUWqyuk14JWaOolLd6D5QW6rBHs=";
    };
  };
  octorus-aarch64-darwin-bin = {
    pname = "octorus-aarch64-darwin-bin";
    version = "0.6.7";
    src = fetchurl {
      url = "https://github.com/ushironoko/octorus/releases/download/v0.6.7/octorus-0.6.7-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-fsqnB49TnsPG9waafix0ILJHjslGJEmAPc2EiJS0g+Y=";
    };
  };
  octorus-aarch64-linux-bin = {
    pname = "octorus-aarch64-linux-bin";
    version = "0.6.7";
    src = fetchurl {
      url = "https://github.com/ushironoko/octorus/releases/download/v0.6.7/octorus-0.6.7-aarch64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-gLo4x5AJbh1dI6sKmwA6ybcYX65pzMO98CroUhepY40=";
    };
  };
  octorus-x86_64-linux-bin = {
    pname = "octorus-x86_64-linux-bin";
    version = "0.6.7";
    src = fetchurl {
      url = "https://github.com/ushironoko/octorus/releases/download/v0.6.7/octorus-0.6.7-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-05KgKIB0oE2f4AYgp4k4GvM5jfIRuVufVZgev8JMVxw=";
    };
  };
  prometheus-jmx-exporter = {
    pname = "prometheus-jmx-exporter";
    version = "1.6.0";
    src = fetchurl {
      url = "https://github.com/prometheus/jmx_exporter/releases/download/v1.6.0/jmx_prometheus_javaagent-1.6.0.jar";
      sha256 = "sha256-qVmD/ZboZdK835EcxQDnyCgIwnq5/SJr+WcytsPYxG4=";
    };
  };
  scriptc = {
    pname = "scriptc";
    version = "v0.0.21";
    src = fetchFromGitHub {
      owner = "vercel-labs";
      repo = "scriptc";
      rev = "v0.0.21";
      fetchSubmodules = false;
      sha256 = "sha256-tagFwu2agc8ES55J3OaK+RFDBX56WAN3iPAE4eMNObE=";
    };
  };
  socks5shim = {
    pname = "socks5shim";
    version = "65d1d643767d2bbc5a2ef9d9350031a2cf0d7289";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "socks5shim";
      rev = "65d1d643767d2bbc5a2ef9d9350031a2cf0d7289";
      fetchSubmodules = false;
      sha256 = "sha256-FdCMVUFK5FHjryFynK89uDShyIdNb24J2HauVJimAMs=";
    };
  };
  starlink-exporter = {
    pname = "starlink-exporter";
    version = "v20250818";
    src = fetchFromGitHub {
      owner = "clarkzjw";
      repo = "starlink_exporter";
      rev = "v20250818";
      fetchSubmodules = false;
      sha256 = "sha256-hPbZC3R9i/ftMrZz727ACY09H3cX91OyJ47YgjM/nS4=";
    };
  };
  xremap-aarch64-linux-bin = {
    pname = "xremap-aarch64-linux-bin";
    version = "0.15.9";
    src = fetchurl {
      url = "https://github.com/xremap/xremap/releases/download/v0.15.9/xremap-linux-aarch64-gnome.zip";
      sha256 = "sha256-Kn5ggBqtrQ0wrer3VjV7A9euQV7qo3nXC7BlgQKLjjc=";
    };
  };
  xremap-x86_64-linux-bin = {
    pname = "xremap-x86_64-linux-bin";
    version = "0.15.9";
    src = fetchurl {
      url = "https://github.com/xremap/xremap/releases/download/v0.15.9/xremap-linux-x86_64-gnome.zip";
      sha256 = "sha256-EIpEOGMhxXX8CtmE8+kaFnPhDalNOqh+k66ZQTjFkAM=";
    };
  };
  yamcel = {
    pname = "yamcel";
    version = "1023a1a84527cd7686451fd344895203c31af746";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "yamcel";
      rev = "1023a1a84527cd7686451fd344895203c31af746";
      fetchSubmodules = false;
      sha256 = "sha256-iiwXt4Hoi9TH6/wV32/aUL2g2P20CsnaJufFHiCzC+E=";
    };
  };
  zlib-rs = {
    pname = "zlib-rs";
    version = "v0.6.6";
    src = fetchFromGitHub {
      owner = "trifectatechfoundation";
      repo = "zlib-rs";
      rev = "v0.6.6";
      fetchSubmodules = false;
      sha256 = "sha256-pLD1DfpR4q6DboLowFig1Q6dJwwI1cOY4RSO3DPaP98=";
    };
    cargoLock."libz-rs-sys-cdylib/Cargo.lock" = {
      lockFile = ./. + "/sha256-pLD1DfpR4q6DboLowFig1Q6dJwwI1cOY4RSO3DPaP98=/libz-rs-sys-cdylib/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
