# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  apple-oss-distributions_berkeleydb = {
    pname = "apple-oss-distributions_berkeleydb";
    version = "BerkeleyDB-29";
    src = fetchFromGitHub {
      owner = "apple-oss-distributions";
      repo = "BerkeleyDB";
      rev = "BerkeleyDB-29";
      fetchSubmodules = false;
      sha256 = "sha256-tHV2BJA7oSCwICyGBMTIKkvMGbYmga3KRY5KgHJrjTg=";
    };
  };
  apple-oss-distributions_curl = {
    pname = "apple-oss-distributions_curl";
    version = "curl-162";
    src = fetchFromGitHub {
      owner = "apple-oss-distributions";
      repo = "curl";
      rev = "curl-162";
      fetchSubmodules = false;
      sha256 = "sha256-JLe7f33RH8NXhQkozlkTYyNeuMtdg5qcvAdBYkxnCnk=";
    };
  };
  apple-oss-distributions_openldap = {
    pname = "apple-oss-distributions_openldap";
    version = "OpenLDAP-559";
    src = fetchFromGitHub {
      owner = "apple-oss-distributions";
      repo = "OpenLDAP";
      rev = "OpenLDAP-559";
      fetchSubmodules = false;
      sha256 = "sha256-zeR8qe+ot5uoyf7yCFYxqEINqCQstrwxrr6Tkfl8weo=";
    };
  };
  apple-oss-distributions_openssh = {
    pname = "apple-oss-distributions_openssh";
    version = "OpenSSH-354.80.3";
    src = fetchFromGitHub {
      owner = "apple-oss-distributions";
      repo = "OpenSSH";
      rev = "OpenSSH-354.80.3";
      fetchSubmodules = false;
      sha256 = "sha256-vHla/rRz6h6PYzdwfn+PiqfaKF1m/A5mCWOlsVhIH20=";
    };
  };
  apple-oss-distributions_zlib = {
    pname = "apple-oss-distributions_zlib";
    version = "zlib-100";
    src = fetchFromGitHub {
      owner = "apple-oss-distributions";
      repo = "zlib";
      rev = "zlib-100";
      fetchSubmodules = false;
      sha256 = "sha256-EAlHKSdWHRbz6F1CjH+jubyEQehSmxE37Ua0iQ4ApcQ=";
    };
  };
  codex-aarch64-darwin-bin = {
    pname = "codex-aarch64-darwin-bin";
    version = "rust-v0.110.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.110.0/codex-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-/ruGxUWNEBqAoXNHyJwPCQemBefKuvL5J68I3zZ8MWE=";
    };
  };
  codex-aarch64-linux-bin = {
    pname = "codex-aarch64-linux-bin";
    version = "rust-v0.110.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.110.0/codex-aarch64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-tMiSp3XK+2kJWQ/w5iHu5QOkrrmM6e7hvZKRvCn9C4g=";
    };
  };
  codex-x86_64-linux-bin = {
    pname = "codex-x86_64-linux-bin";
    version = "rust-v0.110.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.110.0/codex-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-pxplBw39NvhTvHDX3ssFXuXN7vAESQa9PQaY9vIgISQ=";
    };
  };
  displayplacer = {
    pname = "displayplacer";
    version = "v1.4.0";
    src = fetchFromGitHub {
      owner = "jakehilborn";
      repo = "displayplacer";
      rev = "v1.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-BYq8lrS8yE9ARCdAvZxiuC/2vRv6uha++WwKfM37gC0=";
    };
  };
  errorformat = {
    pname = "errorformat";
    version = "223c26dbe2122cc5ce2f3b47400ceaca2b50c496";
    src = fetchFromGitHub {
      owner = "reviewdog";
      repo = "errorformat";
      rev = "223c26dbe2122cc5ce2f3b47400ceaca2b50c496";
      fetchSubmodules = false;
      sha256 = "sha256-kPWojRA7uw8Xv3LDMJRyVB+TpQohmKRrmuRyW+vNWM4=";
    };
  };
  gf-cli = {
    pname = "gf-cli";
    version = "e9e893ff44172eae6e2f87970bf7a28565abedf5";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "gf-cli";
      rev = "e9e893ff44172eae6e2f87970bf7a28565abedf5";
      fetchSubmodules = false;
      sha256 = "sha256-/MMbx6Ebv4A5/BwoFzm0WqMO4X2eoRE+PZto4uSAmUA=";
    };
  };
  gitbucket = {
    pname = "gitbucket";
    version = "4.45.0";
    src = fetchurl {
      url = "https://github.com/gitbucket/gitbucket/releases/download/4.45.0/gitbucket.war";
      sha256 = "sha256-byfgsRcaWkJJaALZbwoGjQ6LR2IJhq1uvaT6E16jhxQ=";
    };
  };
  gogcli = {
    pname = "gogcli";
    version = "v0.11.0";
    src = fetchFromGitHub {
      owner = "steipete";
      repo = "gogcli";
      rev = "v0.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-hJU40ysjRx4p9SWGmbhhpToYCpk3DcMAWCnKqxHRmh0=";
    };
  };
  gws = {
    pname = "gws";
    version = "v0.3.4";
    src = fetchFromGitHub {
      owner = "googleworkspace";
      repo = "cli";
      rev = "v0.3.4";
      fetchSubmodules = false;
      sha256 = "sha256-xPKxsMr0klLeOcfbgtgPCvzAryiOWXhZy2TUU7DrHHQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-xPKxsMr0klLeOcfbgtgPCvzAryiOWXhZy2TUU7DrHHQ=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  hev-socks5-server = {
    pname = "hev-socks5-server";
    version = "2.11.2";
    src = fetchgit {
      url = "https://github.com/heiher/hev-socks5-server.git";
      rev = "2.11.2";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [ ];
      sha256 = "sha256-FHEjO9LaajRH5l4gA7+S/0OI1Pk5WjkSAlrkUJBpsDg=";
    };
  };
  kakehashi = {
    pname = "kakehashi";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "atusy";
      repo = "kakehashi";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-HVc94jpIgyJuEa6zjf2MhNPIHpRkSaoFdZhNdkFWHC0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-HVc94jpIgyJuEa6zjf2MhNPIHpRkSaoFdZhNdkFWHC0=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  kubernetes-mcp-server = {
    pname = "kubernetes-mcp-server";
    version = "v0.0.58";
    src = fetchFromGitHub {
      owner = "containers";
      repo = "kubernetes-mcp-server";
      rev = "v0.0.58";
      fetchSubmodules = false;
      sha256 = "sha256-W/IHZJdq1jlFOD3pqhiqp898k/Obo1/tlXYFSgf2p+Y=";
    };
  };
  libduckdb-aarch64-darwin-bin = {
    pname = "libduckdb-aarch64-darwin-bin";
    version = "v1.4.4";
    src = fetchurl {
      url = "https://install.duckdb.org/v1.4.4/libduckdb-osx-universal.zip";
      sha256 = "sha256-Xm159fuGu9TyTVnO47w48RPRQzdh3zUzfjwBxi7q/iY=";
    };
  };
  libduckdb-aarch64-linux-bin = {
    pname = "libduckdb-aarch64-linux-bin";
    version = "v1.4.4";
    src = fetchurl {
      url = "https://install.duckdb.org/v1.4.4/libduckdb-linux-arm64.zip";
      sha256 = "sha256-do9m4LQIONVnpVJK45Adqkgj9IKf0ebzYV11rlVWK1I=";
    };
  };
  libduckdb-x86_64-linux-bin = {
    pname = "libduckdb-x86_64-linux-bin";
    version = "v1.4.4";
    src = fetchurl {
      url = "https://install.duckdb.org/v1.4.4/libduckdb-linux-amd64.zip";
      sha256 = "sha256-CcwogpWWTYl7R2ZdGJjhbo7xdsrp6mFXl/wTbq4VvV0=";
    };
  };
  octorus = {
    pname = "octorus";
    version = "v0.5.5";
    src = fetchFromGitHub {
      owner = "ushironoko";
      repo = "octorus";
      rev = "v0.5.5";
      fetchSubmodules = false;
      sha256 = "sha256-0MPTLVkTTpMHnIIkBqMqXTG51Pzlu5X9VnNcxTFFaA8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-0MPTLVkTTpMHnIIkBqMqXTG51Pzlu5X9VnNcxTFFaA8=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  perl5 = {
    pname = "perl5";
    version = "v5.43.8";
    src = fetchFromGitHub {
      owner = "Perl";
      repo = "perl5";
      rev = "v5.43.8";
      fetchSubmodules = false;
      sha256 = "sha256-s5bgYEyf/ZiP8ryyVEAMaAVHfJjTbwgn4f5otTSbz/Q=";
    };
  };
  prometheus-jmx-exporter = {
    pname = "prometheus-jmx-exporter";
    version = "1.5.0";
    src = fetchurl {
      url = "https://github.com/prometheus/jmx_exporter/releases/download/1.5.0/jmx_prometheus_javaagent-1.5.0.jar";
      sha256 = "sha256-AxXz9leHYwLGIFqY1ANux3XcpSnF0EGcpg7macaII58=";
    };
  };
  socks5shim = {
    pname = "socks5shim";
    version = "bc0e285ed72e3fb8b3daf4437e9fc33c177e8996";
    src = fetchFromGitHub {
      owner = "johejo";
      repo = "socks5shim";
      rev = "bc0e285ed72e3fb8b3daf4437e9fc33c177e8996";
      fetchSubmodules = false;
      sha256 = "sha256-W2C1ScwZcrXPbeEyxQh0F6rgVLznoPya7Ib4fSCXC70=";
    };
  };
  starlink-exporter = {
    pname = "starlink-exporter";
    version = "v20250818";
    src = fetchFromGitHub {
      owner = "clarkzjw";
      repo = "starlink_exporter";
      rev = "v20250818";
      fetchSubmodules = false;
      sha256 = "sha256-hPbZC3R9i/ftMrZz727ACY09H3cX91OyJ47YgjM/nS4=";
    };
  };
  zlib-rs = {
    pname = "zlib-rs";
    version = "v0.6.3";
    src = fetchFromGitHub {
      owner = "trifectatechfoundation";
      repo = "zlib-rs";
      rev = "v0.6.3";
      fetchSubmodules = false;
      sha256 = "sha256-hNmNLhWfP/fCdCYqa0wIK3ii39kemI7oY8SfjjAqPt8=";
    };
    cargoLock."libz-rs-sys-cdylib/Cargo.lock" = {
      lockFile = ./. + "/sha256-hNmNLhWfP_fCdCYqa0wIK3ii39kemI7oY8SfjjAqPt8=/libz-rs-sys-cdylib/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
